DROP SCHEMA IF EXISTS ${DB_LEGAL_COPILOT_SCHEMA} CASCADE;
CREATE SCHEMA ${DB_LEGAL_COPILOT_SCHEMA};

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE ${DB_LEGAL_COPILOT_SCHEMA}.vector_store (
    id UUID PRIMARY KEY,
    content TEXT,
    metadata JSONB,
    embedding vector(1536)
);